# NumPy Refresher and Portfolio Showcase

## Setup and Notebook Goals

This notebook is designed to be both a complete NumPy refresher and a portfolio piece that demonstrates practical fluency with array creation, vectorized computation, indexing, broadcasting, masking, linear algebra, and visualization-oriented workflows.

In [2]:
# Core numerical computing
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import plotly.graph_objects as go

print("Libraries imported successfully.")

Libraries imported successfully.


## Why NumPy Matters

NumPy is the foundation of scientific computing in Python because it gives us fast, memory-efficient arrays that are far more suitable for numerical work than plain Python lists.

A Python list is flexible, but each element is a separate Python object. NumPy stores values in a compact, homogeneous block of memory, which makes large-scale computation faster and more predictable.

NumPy also enables vectorization, meaning we can apply operations to entire arrays at once instead of looping element by element in pure Python. That leads to cleaner code, fewer bugs, and major performance gains.

It also matters because much of the Python data stack is built on top of it. Libraries such as pandas, matplotlib, scikit-learn, and many machine learning tools rely on NumPy arrays and NumPy-style computation under the hood.

In practice, learning NumPy means learning the core language of data manipulation, numerical analysis, and model preparation in Python.

## Array Creation and Core Data Structures

In [11]:
python_list = [1,2,3,4,5,6,7,8,9,10]
array = np.array(python_list)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array = np.array((1,2,3,4,5))
array

array([1, 2, 3, 4, 5])

## Vectorized Operations and Shape Awareness

In [13]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

print(x+10)
print(x*2)
print(x**2)
print(f"1*1 + 2*2 + 3*3 + ... + 10*10 : {np.dot(x,x)}")
print(np.shape(x))

[11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]
[  1   4   9  16  25  36  49  64  81 100]
1*1 + 2*2 + 3*3 + ... + 10*10 : 385
(10,)


In [5]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
]

nmatrix = np.array(matrix)
print(np.shape(nmatrix))

(4, 3)


## Indexing, Slicing, and Matrix Views

In [24]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix[:,:-1] # all rows and all columns except the last column

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
matrix[1,1] # second row, second column

5

In [ ]:
a, b, c = matrix[2] # matrix decomposition?
print(f"a:{a} b:{b} c:{c}")

a:7 b:8 c:9


In [7]:
nmatrix.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

## Array Utilities, UFuncs, Masking, and Random Sampling

In [8]:
nmatrix.std()

3.452052529534663

In [ ]:
lin = np.arange(10)
lin

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
s = np.sin(lin)
s

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [11]:
print(lin < 2)
print(lin[lin < 2])
print(lin[[True, True, True, False, False, False, False, False, True, True]])

[ True  True False False False False False False False False]
[0 1]
[0 1 2 8 9]


In [12]:
ran = np.random.randint(1, 10, (5,4))
ran

array([[2, 5, 4, 1],
       [6, 3, 4, 5],
       [7, 4, 8, 2],
       [3, 4, 9, 2],
       [8, 2, 1, 5]])

## Iteration, Comprehensions, and Algorithmic Thinking

In [13]:
for r in ran:
    r = r ** 2
    print(r)

[ 4 25 16  1]
[36  9 16 25]
[49 16 64  4]
[ 9 16 81  4]
[64  4  1 25]


In [14]:
for i, r in enumerate(ran):
    print('index(' + str(i) + ') is ', r)

index(0) is  [2 5 4 1]
index(1) is  [6 3 4 5]
index(2) is  [7 4 8 2]
index(3) is  [3 4 9 2]
index(4) is  [8 2 1 5]


In [15]:
l = [x for x in lin if x > 2]
l

[3, 4, 5, 6, 7, 8, 9]

In [16]:
def quick_sort(l):
    if len(l) <= 1:
        return l
        
    arr = np.array(l)
    v = arr[len(arr)//2]
    
    s = arr[arr < v]
    mid = arr[arr == v]
    b = arr[arr > v]
    return np.concatenate([quick_sort(s),mid,quick_sort(b)])

h = [3,1,7,5,6,4,9,2,8]
sorted =quick_sort(h)
sorted

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
not_sorted = np.random.randint(1,1000,(1,18))[0]
print(not_sorted)
sorted = quick_sort(not_sorted)
print(sorted)

[846 860 804 863 398 630 448 962 421 738 871 928  46 601 197 949  23 830]
[ 23  46 197 398 421 448 601 630 738 804 830 846 860 863 871 928 949 962]


## Linear Algebra Essentials

In [ ]:
vector = np.array([1,2,3,4])
print(vector)
print(vector.shape)
print((np.array([1,2,3,4])).dot(np.array([2,2,2,2])))
print(np.dot(vector,vector))

matrix = np.array([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
    [4,4,4,4]
    ])



[1 2 3 4]
(4,)
20
30


## Coordinate Grids and Surface Construction

In [32]:
x = np.linspace(1,10,10)
y = np.linspace(1,10,10)
X, Y = np.meshgrid(x,y)

print(X)
print(Y)
print(np.meshgrid(x,y))

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]
[array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  

In [ ]:
planes = np.array([
    [1,2,1,-2],
    [1,-1,-2,2],
    [2,-2,1,2]
])

x = np.linspace(-10,10,50)
y = np.linspace(-10,10,50)
X, Y = np.meshgrid(x,y)

fig = go.Figure()

colors = ["Viridis","Plasma","Cividis"]

for i in range(3):
    a,b,c,d = planes[i]

    Z = d/c - (a/c)*X - (b/c)*Y

    fig.add_surface(
        x=X,
        y=Y,
        z=Z,
        colorscale=colors[i],
        opacity=0.7,
        showscale=False
    )

fig.update_layout(
    title="Three Planes",
    scene=dict(
        xaxis_title="x",
        yaxis_title="y",
        zaxis_title="z",
        aspectmode="cube"
    )
)

fig.show()



## Wrap-Up and Next Steps

The next step is to turn each section into a polished teaching narrative with short explanations, cleaner examples, and a final mini-project that ties the main NumPy ideas together.