# NumPy Mastery Notebook

This notebook is designed to be used as a refresher for NumPy library and a reference to it's various features.

## How To Use This Notebook

Use each section as a self-contained reference chapter.

- There is a short explanations before code in each section.
- Each section includes both simple demonstrations and realistic use cases.
- When useful, NumPy behavior is compared with plain Python lists.
- End major sections has a compact takeaways or best practices.

## Table of Contents

1. Setup and Notebook Conventions
2. Why NumPy Matters
3. Array Creation Fundamentals
4. Array Inspection and Metadata
5. Shapes, Dimensions, and Reshaping
6. Indexing, Slicing, and Selection
7. Vectorized Computation and Broadcasting
8. Mathematical Functions and Aggregations
9. Boolean Masks and Conditional Logic
10. Sorting, Searching, and Set Operations
11. Iteration, Enumeration, and Practical Patterns
12. Random Number Generation and Sampling
13. Linear Algebra Essentials
14. Coordinate Grids, Simulation Inputs, and Geometry
15. Performance Mindset and Memory Awareness
16. NumPy for Machine Learning Foundations
17. Real Usecase Example
18. Quick Reference Cheat Sheet
19. Closing Notes and Next Steps

## 1. Setup and Notebook Conventions

This section establishes a clean, repeatable working environment for the rest of the notebook.

Notebook conventions used here:

- `numpy` is imported as `np`, following the standard scientific Python convention.
- Optional plotting tools are imported once near the top so later sections stay focused on concepts rather than setup.
- A fixed random seed is used when reproducibility matters.


### Core Imports

These imports cover numerical work, quick inspection, optional visualization, and simple performance measurement support for later sections.

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from time import time

### Reproducibility

Many later sections use random arrays for demonstrations, simulations, and machine learning style examples. Setting a seed helps keep those outputs stable across runs.

In [5]:
SEED = 42
np.random.seed(SEED)
SEED

42

## 2. Why NumPy Matters

NumPy matters because it gives Python a fast, consistent, and expressive way to work with numerical data at scale. If plain Python lists are flexible general-purpose containers, NumPy arrays are specialized tools built for mathematical computing.

A Python list can hold many kinds of objects, which is convenient but less efficient for large numerical workloads. A NumPy array stores values in a homogeneous, compact memory layout, which makes computation faster and more predictable. That difference becomes especially important when datasets grow beyond toy examples.

NumPy also introduces vectorization: instead of writing explicit Python loops for every calculation, we can apply operations to entire arrays at once. This usually leads to code that is shorter, easier to read, and significantly faster because much of the heavy lifting happens in optimized low-level implementations.

Another reason NumPy matters is that it sits underneath much of the modern Python data stack. pandas relies on NumPy-style array structures, matplotlib accepts NumPy arrays naturally, scikit-learn expects NumPy-shaped data, and many machine learning workflows begin with NumPy arrays long before a model is trained.

In practice, learning NumPy is not just about learning one library. It is about learning the core mental model for numerical computing in Python: arrays, shapes, vectorized operations, broadcasting, and matrix-oriented thinking.

Key takeaways:

- NumPy arrays are more efficient than Python lists for numerical work.
- Vectorized operations reduce manual looping and improve performance.
- Many data science and machine learning libraries are built around NumPy concepts.
- Strong NumPy fundamentals make the rest of the Python data ecosystem easier to learn.

## 3. Array Creation Fundamentals

This section shows the core array creation patterns. The goal is to understand which constructor to reach for and what kind of structure it produces.

### Creating Arrays From Python Data

The most direct starting point is converting existing Python sequences into NumPy arrays with `np.array()`.

In [9]:
python_list = [1, 2, 3, 4, 5]
python_tuple = (10, 20, 30, 40)

array_from_list = np.array(python_list)
array_from_tuple = np.array(python_tuple)

print("From list:", array_from_list)
print("From tuple:", array_from_tuple)
print("Type:", type(array_from_list))
print("Dtype:", array_from_list.dtype)

From list: [1 2 3 4 5]
From tuple: [10 20 30 40]
Type: <class 'numpy.ndarray'>
Dtype: int32


### 1D, 2D, and 3D Arrays

Nested sequences define the dimensional structure of the resulting array.

In [22]:
vector_1d = np.array([1, 2, 3, 4])
matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
tensor_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D array:\n", vector_1d)
print("shape:", vector_1d.shape, "| ndim:", vector_1d.ndim)
print()
print("2D array:\n", matrix_2d)
print("shape:", matrix_2d.shape, "| ndim:", matrix_2d.ndim)
print()
print("3D array:\n", tensor_3d)
print("shape:", tensor_3d.shape, "| ndim:", tensor_3d.ndim)

1D array:
 [1 2 3 4]
shape: (4,) | ndim: 1

2D array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3) | ndim: 2

3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2) | ndim: 3


### Generated Numeric Sequences

Use `np.arange()` for step-based ranges and `np.linspace()` when you want a fixed number of evenly spaced values.

In [28]:
print(np.arange(10))
print(np.arange(1,10))
print(np.arange(2,10,2))

print(np.linspace(1,10,20))

# range_values = np.arange(0, 12, 2) # inclusive at start and exclusive at end
# evenly_spaced = np.linspace(0, 1, 6) # inclusive at start and end

# print("np.arange(0, 12, 2):", range_values)
# print("np.linspace(0, 1, 6):", evenly_spaced)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[2 4 6 8]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### Arrays With Default Values

These constructors are useful when you already know the shape you need and want NumPy to fill it efficiently.

In [6]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))
full_array = np.full((2, 3), 7)
empty_array = np.empty((2, 3))
identity_array = np.eye(4)

print("Zeros:\n", zeros_array)
print()
print("Ones:\n", ones_array)
print()
print("Full of 7s:\n", full_array)
print()
print("Empty (uninitialized values):\n", empty_array)
print()
print("Identity matrix:\n", identity_array)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full of 7s:
 [[7 7 7]
 [7 7 7]]

Empty (uninitialized values):
 [[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [2.31421398e-306 1.42413555e-306 1.78019082e-306]]

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Dtypes and Conversions

Controlling `dtype` helps with precision, memory usage, and compatibility with later operations.

In [7]:
int_array = np.array([1, 2, 3, 4], dtype=np.int32)
float_array = np.array([1, 2, 3, 4], dtype=np.float64)
converted_to_float = int_array.astype(np.float64)
back_to_python = float_array.tolist()

print("int_array dtype:", int_array.dtype)
print("float_array dtype:", float_array.dtype)
print("converted_to_float dtype:", converted_to_float.dtype)
print("Back to Python list:", back_to_python)

int_array dtype: int32
float_array dtype: float64
converted_to_float dtype: float64
Back to Python list: [1.0, 2.0, 3.0, 4.0]


Key takeaways:

- `np.array()` bridges Python sequences and NumPy arrays.
- Nested lists naturally create 2D and 3D structures.
- `arange` and `linspace` solve different sequence-generation problems.
- `zeros`, `ones`, `full`, `empty`, and `eye` are core constructors you will use often.
- `dtype` choices and `astype()` conversions are part of everyday NumPy work.

## 4. Array Inspection and Metadata

This section shows how to read an array quickly by inspecting its structure, type, and memory footprint.

In [8]:
sample_vector = np.array([1, 2, 3, 4, 5], dtype=np.int32)
sample_matrix = np.array([[1.5, 2.5, 3.5], [4.5, 5.5, 6.5]])

for name, arr in {"sample_vector": sample_vector, "sample_matrix": sample_matrix}.items():
    print(name)
    print(arr)
    print("shape:", arr.shape)
    print("ndim:", arr.ndim)
    print("size:", arr.size)
    print("dtype:", arr.dtype)
    print("itemsize:", arr.itemsize)
    print("nbytes:", arr.nbytes)
    print("-" * 30)

sample_vector
[1 2 3 4 5]
shape: (5,)
ndim: 1
size: 5
dtype: int32
itemsize: 4
nbytes: 20
------------------------------
sample_matrix
[[1.5 2.5 3.5]
 [4.5 5.5 6.5]]
shape: (2, 3)
ndim: 2
size: 6
dtype: float64
itemsize: 8
nbytes: 48
------------------------------


Quick inspection habits make debugging much easier. If a NumPy result looks wrong, `shape`, `dtype`, and `ndim` are usually the first things to check.

## 5. Shapes, Dimensions, and Reshaping

Reshaping is how we reorganize data without changing the underlying values. This is essential before broadcasting, matrix multiplication, and machine learning preprocessing.

In [9]:
base = np.arange(1, 13)
reshaped = base.reshape(3, 4)
flattened_view = reshaped.ravel()
flattened_copy = reshaped.flatten()
transposed = reshaped.T
column_vector = base.reshape(-1, 1)
expanded = np.expand_dims(base[:4], axis=0)
squeezed = np.squeeze(expanded)

print("base shape:", base.shape)
print("reshaped to 3x4:\n", reshaped)
print("transposed shape:", transposed.shape)
print(transposed)
print("column_vector shape:", column_vector.shape)
print("expanded shape:", expanded.shape)
print(expanded)
print("squeezed shape:", squeezed.shape)
print(squeezed)
print("ravel shares data conceptually as a view when possible:", flattened_view)
print("flatten creates a copy:", flattened_copy)


base shape: (12,)
reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
transposed shape: (4, 3)
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
column_vector shape: (12, 1)
expanded shape: (1, 4)
[[1 2 3 4]]
squeezed shape: (4,)
[1 2 3 4]
ravel shares data conceptually as a view when possible: [ 1  2  3  4  5  6  7  8  9 10 11 12]
flatten creates a copy: [ 1  2  3  4  5  6  7  8  9 10 11 12]


## 6. Indexing, Slicing, and Selection

Indexing is where array fluency becomes practical. Good slicing habits let you pull out rows, columns, windows, and submatrices without extra loops.

In [10]:
grid = np.arange(1, 17).reshape(4, 4)
three_d = np.arange(1, 25).reshape(2, 3, 4)

print("grid:\n", grid)
print("first element:", grid[0, 0])
print("last column:", grid[:, -1])
print("middle block:\n", grid[1:-1, 1:-1])
print("every other row:\n", grid[::2])
print("fancy indexing: (0, 2) and (1, 3) :", grid[[0, 2], [1, 3]] )
print()
print("three_d[1, 2, 3]:", three_d[1, 2, 3])
print("three_d[0, :, 1:3]:\n", three_d[0, :, 1:3])

grid:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
first element: 1
last column: [ 4  8 12 16]
middle block:
 [[ 6  7]
 [10 11]]
every other row:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
fancy indexing: (0, 2) and (1, 3) : [ 2 12]

three_d[1, 2, 3]: 24
three_d[0, :, 1:3]:
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [11]:
original = np.arange(10)
view = original[2:7]
copy = original[2:7].copy()
view[0] = 999
copy[1] = -5

print("original after editing view:", original)
print("view:", view)
print("copy (independent):", copy)

original after editing view: [  0   1 999   3   4   5   6   7   8   9]
view: [999   3   4   5   6]
copy (independent): [ 2 -5  4  5  6]


## 7. Vectorized Computation and Broadcasting

This is one of NumPy's biggest advantages. We can express whole-array operations directly and let optimized routines handle the heavy work.

In [12]:
x = np.arange(1, 6)
y = np.array([10, 20, 30, 40, 50])
manual = np.array([value * 2 + 1 for value in x])
vectorized = x * 2 + 1

print("manual result:", manual)
print("vectorized result:", vectorized)
print("x + y:", x + y)
print("x ** 2:", x ** 2)
print("dot product:", np.dot(x, y))

manual result: [ 3  5  7  9 11]
vectorized result: [ 3  5  7  9 11]
x + y: [11 22 33 44 55]
x ** 2: [ 1  4  9 16 25]
dot product: 550


In [13]:
matrix = np.arange(1, 13).reshape(3, 4)
row_offsets = np.array([100, 200, 300, 400])
column_scale = np.array([[1], [10], [100]])

print("matrix:\n", matrix)
print("matrix + row_offsets:\n", matrix + row_offsets)
print("matrix * column_scale:\n", matrix * column_scale)
print("broadcasted result shape:", (matrix + row_offsets).shape)

matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
matrix + row_offsets:
 [[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]]
matrix * column_scale:
 [[   1    2    3    4]
 [  50   60   70   80]
 [ 900 1000 1100 1200]]
broadcasted result shape: (3, 4)


## 8. Mathematical Functions and Aggregations

NumPy includes both elementwise mathematical functions and summary operations that reduce arrays to useful statistics.

In [14]:
values = np.array([0, 1, 2, 3, 4], dtype=float)
shifted = values + 1

print("shifted:",shifted)
print("sin:", np.round(np.sin(values), 3))
print("cos:", np.round(np.cos(values), 3))
print("exp:", np.round(np.exp(values), 3))
print("log(shifted):", np.round(np.log(shifted), 3))
print("sqrt(shifted):", np.round(np.sqrt(shifted), 3))
print("abs([-3, -1, 2]):", np.abs(np.array([-3, -1, 2])))

shifted: [1. 2. 3. 4. 5.]
sin: [ 0.     0.841  0.909  0.141 -0.757]
cos: [ 1.     0.54  -0.416 -0.99  -0.654]
exp: [ 1.     2.718  7.389 20.086 54.598]
log(shifted): [0.    0.693 1.099 1.386 1.609]
sqrt(shifted): [1.    1.414 1.732 2.    2.236]
abs([-3, -1, 2]): [3 1 2]


In [15]:
scores = np.array([
    [80, 90, 85], 
    [70, 88, 92], 
    [95, 91, 89]])

print("scores:\n", scores)
print("sum:", scores.sum())
print("mean by column:", scores.mean(axis=0))
print("median by row:", np.median(scores, axis=1))
print("std:", np.round(scores.std(), 3))
print("var:", np.round(scores.var(), 3))
print("min and argmin:", scores.min(), scores.argmin())
print("max and argmax:", scores.max(), scores.argmax())
print("cumsum row 0:", np.cumsum(scores[0]))
print("cumprod of [1,2,3,4]:", np.cumprod(np.array([1, 2, 3, 4])))

scores:
 [[80 90 85]
 [70 88 92]
 [95 91 89]]
sum: 780
mean by column: [81.66666667 89.66666667 88.66666667]
median by row: [85. 88. 91.]
std: 7.149
var: 51.111
min and argmin: 70 3
max and argmax: 95 6
cumsum row 0: [ 80 170 255]
cumprod of [1,2,3,4]: [ 1  2  6 24]


## 9. Boolean Masks and Conditional Logic

Boolean arrays make filtering, thresholding, and rule-based transformations concise and expressive.

In [16]:
temperatures = np.array([18, 21, 25, 29, 31, 16, 24])
warm_mask = temperatures >= 24
comfort_mask = (temperatures >= 20) & (temperatures <= 30)

print("temperatures:", temperatures)
print("warm_mask:", warm_mask)
print("warm values:", temperatures[warm_mask])
print("comfortable values:", temperatures[comfort_mask])
print("any above 30?:", np.any(temperatures > 30))
print("all above 15?:", np.all(temperatures > 15))

temperatures: [18 21 25 29 31 16 24]
warm_mask: [False False  True  True  True False  True]
warm values: [25 29 31 24]
comfortable values: [21 25 29 24]
any above 30?: True
all above 15?: True


In [17]:
sensor = np.array([0.2, 0.9, 1.7, 2.5, 3.6, 4.1])
labels = np.where(sensor >= 2.0, "high", "low")
clipped = np.where(sensor > 3.0, 3.0, sensor)

print("sensor:", sensor)
print("labels:", labels)
print("clipped to max 3.0:", clipped)

sensor: [0.2 0.9 1.7 2.5 3.6 4.1]
labels: ['low' 'low' 'low' 'high' 'high' 'high']
clipped to max 3.0: [0.2 0.9 1.7 2.5 3.  3. ]


## 10. Sorting, Searching, and Set Operations

NumPy includes practical tools for ordering values, locating interesting positions, and comparing collections of values.

In [38]:
raw = np.array([7, 2, 9, 2, 5, 7, 1])

print("raw:", raw)
print("sorted:", np.sort(raw))
print("argsort:", np.argsort(raw))
print("unique:", np.unique(raw))
print("indices where raw > 5:", np.where(raw > 5)[0])
print("nonzero indices:", np.nonzero(raw))

raw: [7 2 9 2 5 7 1]
sorted: [1 2 2 5 7 7 9]
argsort: [6 1 3 4 0 5 2]
unique: [1 2 5 7 9]
indices where raw > 5: [0 2 5]
nonzero indices: (array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)


In [19]:
group_a = np.array([1, 2, 3, 4, 5])
group_b = np.array([4, 5, 6, 7])

print("intersection:", np.intersect1d(group_a, group_b))
print("difference a-b:", np.setdiff1d(group_a, group_b))
print("union:", np.union1d(group_a, group_b))
print("membership of [2,6,8] in group_a:", np.isin(np.array([2, 6, 8]), group_a))

intersection: [4 5]
difference a-b: [1 2 3]
union: [1 2 3 4 5 6 7]
membership of [2,6,8] in group_a: [ True False False]


## 11. Iteration, Enumeration, and Practical Patterns

Vectorization is usually best, but iteration still appears when we need row-wise inspection, custom formatting, or small algorithmic routines.

In [20]:
table = np.arange(1, 13).reshape(3, 4)

print("Iterating over rows:")
for row in table:
    print("row sum:", row.sum(), "| row:", row)

print()
print("Iterating with enumerate:")
for idx, row in enumerate(table):
    print(f"row {idx} mean = {row.mean():.2f}")

Iterating over rows:
row sum: 10 | row: [1 2 3 4]
row sum: 26 | row: [5 6 7 8]
row sum: 42 | row: [ 9 10 11 12]

Iterating with enumerate:
row 0 mean = 2.50
row 1 mean = 6.50
row 2 mean = 10.50


In [21]:
def moving_average(arr, window):
    result = []
    for i in range(len(arr) - window + 1):
        result.append(arr[i:i + window].mean())
    return np.array(result)

series = np.array([3, 5, 8, 10, 12, 15])
print("series:", series)
print("moving average window=3:", moving_average(series, 3))

series: [ 3  5  8 10 12 15]
moving average window=3: [ 5.33333333  7.66666667 10.         12.33333333]


## 12. Random Number Generation and Sampling

Random arrays are useful for simulation, testing, and synthetic data generation. Reproducibility matters, so it helps to set a seed intentionally.

In [22]:
np.random.seed(SEED)
uniform = np.random.rand(2, 3)
integers = np.random.randint(1, 10, size=(2, 4))
normal = np.random.normal(loc=0, scale=1, size=5)

print("uniform samples:\n", np.round(uniform, 3))
print("random integers:\n", integers)
print("normal samples:", np.round(normal, 3))

uniform samples:
 [[0.113 0.974 0.729]
 [0.351 0.708 0.8  ]]
random integers:
 [[2 8 3 3]
 [2 8 5 9]]
normal samples: [-0.295 -0.592 -1.394  1.104 -0.932]


In [23]:
np.random.seed(SEED)
feature_1 = np.random.normal(50, 10, size=8)
feature_2 = np.random.normal(100, 15, size=8)
synthetic_dataset = np.column_stack((feature_1, feature_2))

print("synthetic dataset shape:", synthetic_dataset.shape)
print(np.round(synthetic_dataset, 2))

synthetic dataset shape: (8, 2)
[[ 41.52  95.58]
 [ 63.06  91.11]
 [ 59.24  79.09]
 [ 56.4  116.56]
 [ 39.45  86.01]
 [ 67.98  85.85]
 [ 39.87 106.55]
 [ 58.24 111.92]]


## 13. Linear Algebra Essentials

NumPy provides the array operations that underpin regression, optimization, geometry, and many machine learning models.

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
A = np.array([
    [1, 1, 1], 
    [3, 4, 1],
    [1, 1, 1]
    ])
B = np.array([
    [7, 8, 2],
    [9, 10, 2],
    [11, 12, 2]
    ])

print("dot product:", np.dot(a, b))
print("inner product:", np.inner(a, b))
print("matrix multiplication using @:\n", A @ B)
print("matrix multiplication using np.dot:\n", np.dot(A,B))
print("transpose of B:\n", B.T)

dot product: 32
inner product: 32
matrix multiplication using @:
 [[27 30  6]
 [68 76 16]
 [27 30  6]]
matrix multiplication using np.dot:
 [[27 30  6]
 [68 76 16]
 [27 30  6]]
transpose of B:
 [[ 7  9 11]
 [ 8 10 12]
 [ 2  2  2]]


In [25]:
M = np.array([
    [2.0, 1.0], 
    [1.0, 3.0]
    ])
target = np.array([1.0, 2.0])
solution = np.linalg.solve(M, target) # solve will raise exception if there is no explicit solution.

print("solution to Mx = target:", np.round(solution, 3))
print("determinant:", np.round(np.linalg.det(M), 3))
print("inverse:\n", np.round(np.linalg.inv(M), 3))
print("rank:", np.linalg.matrix_rank(M))
eigenvalues, eigenvectors = np.linalg.eig(M)
print("eigenvalues:", np.round(eigenvalues, 3))
print("eigenvectors:\n", np.round(eigenvectors, 3))

solution to Mx = target: [0.2 0.6]
determinant: 5.0
inverse:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
rank: 2
eigenvalues: [1.382 3.618]
eigenvectors:
 [[-0.851 -0.526]
 [ 0.526 -0.851]]


## 14. Coordinate Grids, Simulation Inputs, and Geometry

Coordinate grids make it easy to evaluate formulas across whole 2D domains. This is useful in plotting, simulation, optimization, and geometry.

In [26]:
x = np.linspace(-2, 2, 5)
y = np.linspace(-2, 2, 5)
X, Y = np.meshgrid(x, y)
Z = X**2 + Y**2

print("x: ", x ,"\ny: ", y)
print("X:\n", X)
print("Y:\n", Y)
print("X shape:", X.shape)
print("Y shape:", Y.shape)
print("surface Z = X^2 + Y^2:\n", Z)

x:  [-2. -1.  0.  1.  2.] 
y:  [-2. -1.  0.  1.  2.]
X:
 [[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
Y:
 [[-2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]]
X shape: (5, 5)
Y shape: (5, 5)
surface Z = X^2 + Y^2:
 [[8. 5. 4. 5. 8.]
 [5. 2. 1. 2. 5.]
 [4. 1. 0. 1. 4.]
 [5. 2. 1. 2. 5.]
 [8. 5. 4. 5. 8.]]


In [27]:
x_line = np.linspace(0, 4, 5)
y_line = np.linspace(0, 4, 5)
X_plane, Y_plane = np.meshgrid(x_line, y_line)
plane = 2 * X_plane + 3 * Y_plane + 5

print("plane values for z = 2x + 3y + 5:\n", plane)
print("center point value:", plane[2, 2])

plane values for z = 2x + 3y + 5:
 [[ 5.  7.  9. 11. 13.]
 [ 8. 10. 12. 14. 16.]
 [11. 13. 15. 17. 19.]
 [14. 16. 18. 20. 22.]
 [17. 19. 21. 23. 25.]]
center point value: 15.0


## 15. Performance Mindset and Memory Awareness

A good NumPy workflow is not only correct; it is also conscious of speed, memory, and whether operations create views or copies.

In [28]:
large = np.arange(1000000, dtype=np.float64)
view = large[:5]
copy = large[:5].copy()

print("large dtype:", large.dtype)
print("large nbytes:", large.nbytes)
print("first five via view:", view)
print("copy shares memory?", np.shares_memory(large, copy))
print("view shares memory?", np.shares_memory(large, view))

large dtype: float64
large nbytes: 8000000
first five via view: [0. 1. 2. 3. 4.]
copy shares memory? False
view shares memory? True


In [29]:
small = np.arange(1, 3000001)
t = time()
python_sum = sum([value * 2 for value in small])
print("python time: ", time()-t)
t = time()
numpy_sum = np.sum(small * 2)
print("numpy time: ", time()-t)

print("python_sum:", python_sum)
print("numpy_sum:", numpy_sum)
print("same result:", python_sum == numpy_sum)
print("Vectorized NumPy usually wins more clearly as data gets larger.")

python time:  0.4072227478027344
numpy time:  0.0
python_sum: 2046514880
numpy_sum: 2046514880
same result: True
Vectorized NumPy usually wins more clearly as data gets larger.


C:\Users\Reza\AppData\Local\Temp\ipykernel_23452\190949583.py:3: RuntimeWarning: overflow encountered in scalar add
  python_sum = sum([value * 2 for value in small])


## 16. NumPy for Machine Learning Foundations

Many machine learning workflows start as plain array operations: building feature matrices, transforming columns, and applying matrix math to predictions.

In [30]:
features = np.array([
    [170, 65],
    [180, 80],
    [175, 72],
    [160, 55]
], dtype=float)
target = np.array([0, 1, 1, 0])

feature_means = features.mean(axis=0)
feature_stds = features.std(axis=0)
standardized = (features - feature_means) / feature_stds

print("features shape:", features.shape)
print("target shape:", target.shape)
print("means:", np.round(feature_means, 2))
print("stds:", np.round(feature_stds, 2))
print("standardized features:\n", np.round(standardized, 3))

features shape: (4, 2)
target shape: (4,)
means: [171.25  68.  ]
stds: [7.4  9.19]
standardized features:
 [[-0.169 -0.326]
 [ 1.183  1.305]
 [ 0.507  0.435]
 [-1.521 -1.414]]


In [31]:
X = np.array([
    [1, 1.0, 2.0],
    [1, 2.0, 1.0],
    [1, 3.0, 4.0]
])
weights = np.array([0.5, 1.2, -0.7])
predictions = X @ weights

print("design matrix X:\n", X)
print("weights:", weights)
print("predictions:", np.round(predictions, 3))

design matrix X:
 [[1. 1. 2.]
 [1. 2. 1.]
 [1. 3. 4.]]
weights: [ 0.5  1.2 -0.7]
predictions: [0.3 2.2 1.3]


## 17. Real Usecase Example

In [32]:
np.random.seed(SEED)
study_hours = np.random.randint(1, 10, size=12)
practice_tests = np.random.randint(50, 100, size=12)
exam_scores = 5 * study_hours + 0.4 * practice_tests + np.random.normal(0, 3, size=12)
student_data = np.column_stack((study_hours, practice_tests, exam_scores))

print("columns = study_hours, practice_tests, exam_scores")
print(np.round(student_data, 2))
print("top 3 exam scores:", np.round(np.sort(student_data[:, 2])[-3:], 2))

columns = study_hours, practice_tests, exam_scores
[[ 8.   76.   68.13]
 [ 7.   93.   75.1 ]
 [ 8.   51.   60.68]
 [ 9.   73.   79.98]
 [ 9.   58.   68.87]
 [ 4.   91.   49.58]
 [ 1.   91.   39.85]
 [ 8.   51.   61.48]
 [ 1.   98.   47.3 ]
 [ 8.   59.   63.99]
 [ 8.   78.   73.87]
 [ 2.   84.   43.48]]
top 3 exam scores: [73.87 75.1  79.98]


Best practices:

- Check `shape` before arithmetic and matrix operations.
- Use `.copy()` when you need independence from the original array.
- Be explicit about `dtype` when precision matters.
- Prefer vectorized operations over manual Python loops when possible.
- Print small slices and metadata when debugging instead of staring at full arrays.

## 18. Quick Reference Cheat Sheet

This section is a compact review page for the operations that come up most often.

Core patterns to remember:

- Create arrays: `np.array`, `np.arange`, `np.linspace`, `np.zeros`, `np.ones`, `np.full`, `np.eye`
- Inspect arrays: `.shape`, `.ndim`, `.size`, `.dtype`, `.nbytes`
- Reshape arrays: `.reshape`, `.ravel`, `.flatten`, `.T`, `np.expand_dims`, `np.squeeze`
- Aggregate values: `.sum`, `.mean`, `np.median`, `.std`, `.min`, `.max`, `.argmin`, `.argmax`
- Filter values: comparisons, boolean masks, `np.where`, `np.any`, `np.all`
- Linear algebra: `np.dot`, `@`, `np.linalg.solve`, `np.linalg.det`, `np.linalg.inv`, `np.linalg.eig`

In [33]:
quick = np.arange(1, 10).reshape(3, 3)

print("quick array:\n", quick)
print("shape:", quick.shape)
print("transpose:\n", quick.T)
print("row means:", quick.mean(axis=1))
print("values > 5:", quick[quick > 5])
print("determinant:", np.linalg.det(quick))

quick array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
row means: [2. 5. 8.]
values > 5: [6 7 8 9]
determinant: 0.0


## 19. Closing Notes and Next Steps

This notebook demonstrates the main NumPy skills that show up again and again in data work: creation, inspection, reshaping, indexing, vectorization, masking, linear algebra, and ML-oriented array thinking.

Key habits worth carrying forward:

- Think in arrays and shapes, not one element at a time.
- Inspect metadata early when debugging.
- Prefer vectorized transformations when possible.
- Stay aware of views, copies, and `dtype` choices.
- Connect every operation back to a real use case such as cleaning data, building features, simulation, or modeling.

Next notebooks to checkout after this one are pandas, and visualization libraries from the complete notebook series.
Also don't forget to check out the common machine learning algorithms built from scratch series including PCA, linear regression, and Neural Nets.