# NumPy Mastery Notebook

This notebook is designed as a refresher and practical reference for NumPy, with an ML-engineering focus and project-level polish for portfolio use.

## How To Use This Notebook

Use each section as a self-contained reference chapter.

- There is a short explanations before code in each section.
- Each section includes both simple demonstrations and realistic use cases.
- When useful, NumPy behavior is compared with plain Python lists.
- End major sections has a compact takeaways or best practices.

## Table of Contents

1. Setup and Notebook Conventions
2. Why NumPy Matters
3. Array Creation Fundamentals
4. Array Inspection and Metadata
5. Shapes, Dimensions, and Reshaping
6. Indexing, Slicing, and Selection
7. Vectorized Computation and Broadcasting
8. Mathematical Functions and Aggregations
9. Boolean Masks and Conditional Logic
10. Sorting, Searching, and Set Operations
11. Iteration, Enumeration, and Practical Patterns
12. Random Number Generation and Sampling
13. Linear Algebra Essentials
14. Coordinate Grids, Simulation Inputs, and Geometry
15. Performance Mindset and Memory Awareness
16. NumPy for Machine Learning Foundations
17. Real Usecase Example
18. Quick Reference Cheat Sheet
19. Closing Notes and Next Steps

New high-impact additions in this version include: modern random API (`default_rng`), array stacking/splitting, missing-value handling, axis + `keepdims` patterns, top-k selection with `argpartition`, stronger ML-focused linear algebra (`norm`, `lstsq`, `pinv`, `svd`, `eigh`), `einsum`/`tensordot`, numerical stability, memory contiguity, save/load workflows, and numerical comparison utilities.

## 1. Setup and Notebook Conventions

This section establishes a clean, repeatable working environment for the rest of the notebook.

Notebook conventions used here:

- `numpy` is imported as `np`, following the standard scientific Python convention.
- Optional plotting tools are imported once near the top so later sections stay focused on concepts rather than setup.
- A fixed random seed is used when reproducibility matters.


### Core Imports

These imports cover numerical work, quick inspection, optional visualization, and simple performance measurement support for later sections.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from time import time

### Reproducibility

Many later sections use random arrays for demonstrations, simulations, and ML-style examples. We use NumPy's modern Generator API (`default_rng`) for reproducible randomness without relying on global RNG state.

In [2]:
SEED = 47
rng = np.random.default_rng(SEED)
print('Seed:', SEED)
rng

Seed: 47


Generator(PCG64) at 0x27316304900

## 2. Why NumPy Matters

NumPy matters because it gives Python a fast, consistent, and expressive way to work with numerical data at scale. If plain Python lists are flexible general-purpose containers, NumPy arrays are specialized tools built for mathematical computing.

A Python list can hold many kinds of objects, which is convenient but less efficient for large numerical workloads. A NumPy array stores values in a homogeneous, compact memory layout, which makes computation faster and more predictable. That difference becomes especially important when datasets grow beyond toy examples.

NumPy also introduces vectorization: instead of writing explicit Python loops for every calculation, we can apply operations to entire arrays at once. This usually leads to code that is shorter, easier to read, and significantly faster because much of the heavy lifting happens in optimized low-level implementations.

Another reason NumPy matters is that it sits underneath much of the modern Python data stack. pandas relies on NumPy-style array structures, matplotlib accepts NumPy arrays naturally, scikit-learn expects NumPy-shaped data, and many machine learning workflows begin with NumPy arrays long before a model is trained.

In practice, learning NumPy is not just about learning one library. It is about learning the core mental model for numerical computing in Python: arrays, shapes, vectorized operations, broadcasting, and matrix-oriented thinking.

Key takeaways:

- NumPy arrays are more efficient than Python lists for numerical work.
- Vectorized operations reduce manual looping and improve performance.
- Many data science and machine learning libraries are built around NumPy concepts.
- Strong NumPy fundamentals make the rest of the Python data ecosystem easier to learn.

## 3. Array Creation Fundamentals

This section shows the core array creation patterns. The goal is to understand which constructor to reach for and what kind of structure it produces.

### Creating Arrays From Python Data

The most direct starting point is converting existing Python sequences into NumPy arrays with `np.array()`.

In [3]:
python_list = [1, 2, 3, 4, 5]
python_tuple = (10, 20, 30, 40)

array_from_list = np.array(python_list)
array_from_tuple = np.array(python_tuple)

print("From list:", array_from_list)
print("From tuple:", array_from_tuple)
print("Type:", type(array_from_list))
print("Dtype:", array_from_list.dtype)

From list: [1 2 3 4 5]
From tuple: [10 20 30 40]
Type: <class 'numpy.ndarray'>
Dtype: int32


### 1D, 2D, and 3D Arrays

Nested sequences define the dimensional structure of the resulting array.

In [4]:
vector_1d = np.array([1, 2, 3, 4])
matrix_2d = np.array([[1, 2, 3], [4, 5, 6]])
tensor_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D array:\n", vector_1d)
print("shape:", vector_1d.shape, "| ndim:", vector_1d.ndim)
print()
print("2D array:\n", matrix_2d)
print("shape:", matrix_2d.shape, "| ndim:", matrix_2d.ndim)
print()
print("3D array:\n", tensor_3d)
print("shape:", tensor_3d.shape, "| ndim:", tensor_3d.ndim)

1D array:
 [1 2 3 4]
shape: (4,) | ndim: 1

2D array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3) | ndim: 2

3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2) | ndim: 3


### Generated Numeric Sequences

Use `np.arange()` for step-based ranges and `np.linspace()` when you want a fixed number of evenly spaced values.

In [5]:
range_values = np.arange(0, 12, 2) # inclusive at start and exclusive at end
evenly_spaced = np.linspace(0, 1, 6) # inclusive at start and end

print("np.arange(0, 12, 2):", range_values)
print("np.linspace(0, 1, 6):", evenly_spaced)

np.arange(0, 12, 2): [ 0  2  4  6  8 10]
np.linspace(0, 1, 6): [0.  0.2 0.4 0.6 0.8 1. ]


### Arrays With Default Values

These constructors are useful when you already know the shape you need and want NumPy to fill it efficiently.

In [6]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))
full_array = np.full((2, 3), 7)
empty_array = np.empty((2, 3))
identity_array = np.eye(4)

print("Zeros:\n", zeros_array)
print()
print("Ones:\n", ones_array)
print()
print("Full of 7s:\n", full_array)
print()
print("Empty (uninitialized values):\n", empty_array)
print()
print("Identity matrix:\n", identity_array)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full of 7s:
 [[7 7 7]
 [7 7 7]]

Empty (uninitialized values):
 [[4.47543482e+217 6.80648771e+199 3.03181447e+180]
 [4.56969612e+233 5.20073590e+098 6.82718679e-313]]

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Dtypes and Conversions

Controlling `dtype` helps with precision, memory usage, and compatibility with later operations.

In [7]:
int_array = np.array([1, 2, 3, 4], dtype=np.int32)
float_array = np.array([1, 2, 3, 4], dtype=np.float64)
converted_to_float = int_array.astype(np.float64)
back_to_python = float_array.tolist()

print("int_array dtype:", int_array.dtype)
print("float_array dtype:", float_array.dtype)
print("converted_to_float dtype:", converted_to_float.dtype)
print("Back to Python list:", back_to_python)

int_array dtype: int32
float_array dtype: float64
converted_to_float dtype: float64
Back to Python list: [1.0, 2.0, 3.0, 4.0]


Key takeaways:

- `np.array()` bridges Python sequences and NumPy arrays.
- Nested lists naturally create 2D and 3D structures.
- `arange` and `linspace` solve different sequence-generation problems.
- `zeros`, `ones`, `full`, `empty`, and `eye` are core constructors you will use often.
- `dtype` choices and `astype()` conversions are part of everyday NumPy work.

## 4. Array Inspection and Metadata

This section shows how to read an array quickly by inspecting its structure, type, and memory footprint.

In [8]:
sample_vector = np.array([1, 2, 3, 4, 5], dtype=np.int32)
sample_matrix = np.array([[1.5, 2.5, 3.5], [4.5, 5.5, 6.5]])

for name, arr in {"sample_vector": sample_vector, "sample_matrix": sample_matrix}.items():
    print(name)
    print(arr)
    print("shape:", arr.shape)
    print("ndim:", arr.ndim)
    print("size:", arr.size)
    print("dtype:", arr.dtype)
    print("itemsize:", arr.itemsize)
    print("nbytes:", arr.nbytes)
    print("-" * 30)

sample_vector
[1 2 3 4 5]
shape: (5,)
ndim: 1
size: 5
dtype: int32
itemsize: 4
nbytes: 20
------------------------------
sample_matrix
[[1.5 2.5 3.5]
 [4.5 5.5 6.5]]
shape: (2, 3)
ndim: 2
size: 6
dtype: float64
itemsize: 8
nbytes: 48
------------------------------


Quick inspection habits make debugging much easier. If a NumPy result looks wrong, `shape`, `dtype`, and `ndim` are usually the first things to check.

## 5. Shapes, Dimensions, and Reshaping

Reshaping is how we reorganize data without changing the underlying values. This is essential before broadcasting, matrix multiplication, and machine learning preprocessing.

Flatten returns a copy while ravel just returns a view. So if you do some changes to the output of flatten, the original numpy array will remain intact. But, changes to the view affects the original array, though both methods do the same operation to a numpy array.

In [9]:
base = np.arange(1, 13)
reshaped = base.reshape(3, 4)
flattened_view = reshaped.ravel()
flattened_copy = reshaped.flatten()
transposed = reshaped.T
column_vector = base.reshape(-1, 1)
expanded = np.expand_dims(base[:4], axis=0)
squeezed = np.squeeze(expanded)

print("base shape:", base.shape)
print("reshaped to 3x4:\n", reshaped)
print("transposed shape:", transposed.shape)
print(transposed)
print("column_vector shape:", column_vector.shape)
print("expanded shape:", expanded.shape)
print(expanded)
print("squeezed shape:", squeezed.shape)
print(squeezed)
print("ravel shares data conceptually as a view when possible:", flattened_view)
print("flatten creates a copy:", flattened_copy)


base shape: (12,)
reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
transposed shape: (4, 3)
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
column_vector shape: (12, 1)
expanded shape: (1, 4)
[[1 2 3 4]]
squeezed shape: (4,)
[1 2 3 4]
ravel shares data conceptually as a view when possible: [ 1  2  3  4  5  6  7  8  9 10 11 12]
flatten creates a copy: [ 1  2  3  4  5  6  7  8  9 10 11 12]


### Shape Engineering Patterns for ML

**What this solves:** Most ML bugs come from shape mismatches, not math.

**How to use it:**
- Use `[:, np.newaxis]` to convert `(n,)` into a column vector `(n, 1)`.
- Use `[np.newaxis, :]` to make a row vector `(1, n)`.
- Add a batch axis when a model expects batch-first input.

**Important:** Keep a consistent mental convention such as `(batch, features)` and check `.shape` before arithmetic.

In [10]:
v = np.array([10, 20, 30, 40])

as_column = v[:, np.newaxis]      # shape (n, 1)
as_row = v[np.newaxis, :]         # shape (1, n)
with_batch = np.expand_dims(v, axis=0)  # shape (1, n)

print('v shape:', v.shape)
print('column shape (n,1):', as_column.shape)
print('row shape (1,n):', as_row.shape)
print('with batch axis:', with_batch.shape)

# Typical feature layout: (batch_size, n_features)
batch_features = np.array([[1.0, 2.0, 3.0], [2.0, 3.0, 5.0], [4.0, 6.0, 9.0]])
print('batch_features shape:', batch_features.shape)

v shape: (4,)
column shape (n,1): (4, 1)
row shape (1,n): (1, 4)
with batch axis: (1, 4)
batch_features shape: (3, 3)


### Concatenation, Stacking, and Splitting

**What this solves:** Real ML pipelines constantly combine and split arrays (features, batches, train/val slices).

**How to use it:**
- `concatenate` joins along an existing axis.
- `stack` adds a new axis.
- `vstack/hstack` are shorthand for common 2D joins.
- `split/hsplit/vsplit` separate arrays into chunks.

**Important:** Most errors here are axis/shape mismatches, so inspect shapes before joining.

In [11]:
left = np.array([[1, 2], [3, 4]])
right = np.array([[10, 20], [30, 40]])

print('concatenate axis=0:\n', np.concatenate([left, right], axis=0))
print('concatenate axis=1:\n', np.concatenate([left, right], axis=1))

print('stack axis=0 shape:', np.stack([left, right], axis=0).shape)
print('vstack:\n', np.vstack([left, right]))
print('hstack:\n', np.hstack([left, right]))
print('column_stack from vectors:\n', np.column_stack([np.array([1, 2, 3]), np.array([4, 5, 6])]))

split_source = np.arange(12).reshape(3, 4)
left_half, right_half = np.hsplit(split_source, 2)
print('split_source:\n', split_source)
print('hsplit left:\n', left_half)
print('hsplit right:\n', right_half)

concatenate axis=0:
 [[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]
concatenate axis=1:
 [[ 1  2 10 20]
 [ 3  4 30 40]]
stack axis=0 shape: (2, 2, 2)
vstack:
 [[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]
hstack:
 [[ 1  2 10 20]
 [ 3  4 30 40]]
column_stack from vectors:
 [[1 4]
 [2 5]
 [3 6]]
split_source:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
hsplit left:
 [[0 1]
 [4 5]
 [8 9]]
hsplit right:
 [[ 2  3]
 [ 6  7]
 [10 11]]


## 6. Indexing, Slicing, and Selection

Indexing is where array fluency becomes practical. Good slicing habits let you pull out rows, columns, windows, and submatrices without extra loops.

In [12]:
grid = np.arange(1, 17).reshape(4, 4)
three_d = np.arange(1, 25).reshape(2, 3, 4)

print("grid:\n", grid)
print("first element:", grid[0, 0])
print("last column:", grid[:, -1])
print("middle block:\n", grid[1:-1, 1:-1])
print("every other row:\n", grid[::2])
print("even rows and columns:\n", grid[::2,::2])
print("fancy indexing: (0, 2) and (1, 3) x1:(0,1), x2:(2,3) :", grid[[0, 2], [1, 3]] )
print()
print("three_d[1, 2, 3]:", three_d[1, 2, 3])
print("three_d[0, :, 1:3]:\n", three_d[0, :, 1:3])

grid:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
first element: 1
last column: [ 4  8 12 16]
middle block:
 [[ 6  7]
 [10 11]]
every other row:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
even rows and columns:
 [[ 1  3]
 [ 9 11]]
fancy indexing: (0, 2) and (1, 3) x1:(0,1), x2:(2,3) : [ 2 12]

three_d[1, 2, 3]: 24
three_d[0, :, 1:3]:
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [13]:
original = np.arange(10)
view = original[2:7]
copy = original[2:7].copy()
view[0] = 999
copy[1] = -5

print("original after editing view:", original)
print("view:", view)
print("copy (independent):", copy)

original after editing view: [  0   1 999   3   4   5   6   7   8   9]
view: [999   3   4   5   6]
copy (independent): [ 2 -5  4  5  6]


### Advanced Indexing for Real Workflows

**What this solves:** Selecting custom rows/columns and updating specific positions without loops.

**How to use it:**
- Index arrays to pick minibatches or feature subsets.
- `np.ix_` builds row/column grids for submatrices.
- `np.take` and `np.put` are explicit gather/scatter helpers.
- Boolean assignment applies rule-based updates in place.

**Important:** Advanced indexing usually creates copies, while slicing often returns views.

In [14]:
A = np.arange(1, 21).reshape(5, 4)
row_idx = np.array([0, 2, 4])
col_idx = np.array([1, 3])

print('A:\n', A)
print('selected rows:\n', A[row_idx])
print('selected columns:\n', A[:, col_idx])

# np.ix_ builds cartesian index grids for submatrices.
print('submatrix with np.ix_:\n', A[np.ix_(row_idx, col_idx)])

picked = np.take(A, indices=[0, 5, 10, 15])
print('np.take flat picks:', picked)

A_copy = A.copy()
np.put(A_copy, [0, 3, 6], [-1, -2, -3])
A_copy[A_copy % 2 == 0] = 0  # boolean assignment
print('after np.put + boolean assignment:\n', A_copy)

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
selected rows:
 [[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]]
selected columns:
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
submatrix with np.ix_:
 [[ 2  4]
 [10 12]
 [18 20]]
np.take flat picks: [ 1  6 11 16]
after np.put + boolean assignment:
 [[-1  0  3  0]
 [ 5  0 -3  0]
 [ 9  0 11  0]
 [13  0 15  0]
 [17  0 19  0]]


## 7. Vectorized Computation and Broadcasting

This is one of NumPy's biggest advantages. We can express whole-array operations directly and let optimized routines handle the heavy work.

In [15]:
x = np.arange(1, 6)
y = np.array([10, 20, 30, 40, 50])
manual = np.array([value * 2 + 1 for value in x])
vectorized = x * 2 + 1

print("manual result:", manual)
print("vectorized result:", vectorized)
print("x + y:", x + y)
print("x ** 2:", x ** 2)
print("dot product:", np.dot(x, y))

manual result: [ 3  5  7  9 11]
vectorized result: [ 3  5  7  9 11]
x + y: [11 22 33 44 55]
x ** 2: [ 1  4  9 16 25]
dot product: 550


In [16]:
matrix = np.arange(1, 13).reshape(3, 4)
row_offsets = np.array([100, 200, 300, 400])
column_scale = np.array([[1], [10], [100]])

print("matrix:\n", matrix)
print("matrix + row_offsets:\n", matrix + row_offsets)
print("matrix * column_scale:\n", matrix * column_scale)
print("broadcasted result shape:", (matrix + row_offsets).shape)

matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
matrix + row_offsets:
 [[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]]
matrix * column_scale:
 [[   1    2    3    4]
 [  50   60   70   80]
 [ 900 1000 1100 1200]]
broadcasted result shape: (3, 4)


## 8. Mathematical Functions and Aggregations

NumPy includes both elementwise mathematical functions and summary operations that reduce arrays to useful statistics.

In [17]:
values = np.array([0, 1, 2, 3, 4], dtype=float)
shifted = values + 1

print("shifted:",shifted)
print("sin:", np.round(np.sin(values), 3))
print("cos:", np.round(np.cos(values), 3))
print("exp:", np.round(np.exp(values), 3))
print("log(shifted):", np.round(np.log(shifted), 3))
print("sqrt(shifted):", np.round(np.sqrt(shifted), 3))
print("abs([-3, -1, 2]):", np.abs(np.array([-3, -1, 2])))

shifted: [1. 2. 3. 4. 5.]
sin: [ 0.     0.841  0.909  0.141 -0.757]
cos: [ 1.     0.54  -0.416 -0.99  -0.654]
exp: [ 1.     2.718  7.389 20.086 54.598]
log(shifted): [0.    0.693 1.099 1.386 1.609]
sqrt(shifted): [1.    1.414 1.732 2.    2.236]
abs([-3, -1, 2]): [3 1 2]


In [18]:
scores = np.array([
    [80, 90, 85], 
    [70, 88, 92], 
    [95, 91, 89]])

print("scores:\n", scores)
print("sum:", scores.sum())
print("mean by column:", scores.mean(axis=0))
print("median by row:", np.median(scores, axis=1))
print("std:", np.round(scores.std(), 3))
print("var:", np.round(scores.var(), 3))
print("min and argmin:", scores.min(), scores.argmin())
print("max and argmax:", scores.max(), scores.argmax())
print("cumsum row 0:", np.cumsum(scores[0]))
print("cumprod of [1,2,3,4]:", np.cumprod(np.array([1, 2, 3, 4])))

scores:
 [[80 90 85]
 [70 88 92]
 [95 91 89]]
sum: 780
mean by column: [81.66666667 89.66666667 88.66666667]
median by row: [85. 88. 91.]
std: 7.149
var: 51.111
min and argmin: 70 3
max and argmax: 95 6
cumsum row 0: [ 80 170 255]
cumprod of [1,2,3,4]: [ 1  2  6 24]


### Axis Semantics and `keepdims`

**What this solves:** Correct row-wise/column-wise reductions and stable broadcasting afterward.

**How to use it:**
- `axis=0`: reduce down rows (column statistics).
- `axis=1`: reduce across columns (row statistics).
- `keepdims=True`: preserve reduced dimensions so subtraction/division broadcasts safely.

**Important:** `keepdims` is a simple way to avoid reshape clutter in normalization code.

In [19]:
X = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])

col_means = X.mean(axis=0)
row_means = X.mean(axis=1)
row_means_keep = X.mean(axis=1, keepdims=True)
centered_by_row = X - row_means_keep

print('X:\n', X)
print('column means shape:', col_means.shape, col_means)
print('row means shape:', row_means.shape, row_means)
print('row means keepdims shape:', row_means_keep.shape)
print('centered by row:\n', centered_by_row)
print('row-centered means:', np.round(centered_by_row.mean(axis=1), 8))

X:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
column means shape: (3,) [4. 5. 6.]
row means shape: (3,) [2. 5. 8.]
row means keepdims shape: (3, 1)
centered by row:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
row-centered means: [0. 0. 0.]


## 9. Boolean Masks and Conditional Logic

Boolean arrays make filtering, thresholding, and rule-based transformations concise and expressive.

In [20]:
temperatures = np.array([18, 21, 25, 29, 31, 16, 24])
warm_mask = temperatures >= 24
comfort_mask = (temperatures >= 20) & (temperatures <= 30)

print("temperatures:", temperatures)
print("warm_mask:", warm_mask)
print("warm values:", temperatures[warm_mask])
print("comfortable values:", temperatures[comfort_mask])
print("any above 30?:", np.any(temperatures > 30))
print("all above 15?:", np.all(temperatures > 15))

temperatures: [18 21 25 29 31 16 24]
warm_mask: [False False  True  True  True False  True]
warm values: [25 29 31 24]
comfortable values: [21 25 29 24]
any above 30?: True
all above 15?: True


In [21]:
sensor = np.array([0.2, 0.9, 1.7, 2.5, 3.6, 4.1])
labels = np.where(sensor >= 2.0, "high", "low")
clipped = np.where(sensor > 3.0, 3.0, sensor)

print("sensor:", sensor)
print("labels:", labels)
print("clipped to max 3.0:", clipped)

sensor: [0.2 0.9 1.7 2.5 3.6 4.1]
labels: ['low' 'low' 'low' 'high' 'high' 'high']
clipped to max 3.0: [0.2 0.9 1.7 2.5 3.  3. ]


### Missing Values, NaNs, and Finite Checks

**What this solves:** Real data contains `NaN`, `inf`, and `-inf`, which can silently break stats.

**How to use it:**
- Detect with `np.isnan` and `np.isfinite`.
- Use NaN-aware reducers (`nanmean`, `nanstd`, `nansum`) after masking non-finite values.
- Impute with `np.where` when needed.

**Important:** `nan*` functions ignore `NaN`, but they do not automatically ignore `inf`/`-inf`.

In [22]:
raw = np.array([1.0, np.nan, 3.5, np.inf, -np.inf, 5.0])

print('raw:', raw)
print('isnan:', np.isnan(raw))
print('isfinite:', np.isfinite(raw))

# Keep only finite values for clean aggregation.
finite_vals = raw[np.isfinite(raw)]
clean_for_nan_funcs = np.where(np.isfinite(raw), raw, np.nan)
print('finite values:', finite_vals)
print('nanmean (finite only):', np.nanmean(clean_for_nan_funcs))
print('nanstd (finite only):', np.nanstd(clean_for_nan_funcs))
print('nansum (finite only):', np.nansum(clean_for_nan_funcs))

# Simple imputation: replace non-finite values with finite mean.
finite_mean = finite_vals.mean()
imputed = np.where(np.isfinite(raw), raw, finite_mean)
print('imputed:', np.round(imputed, 3))

raw: [ 1.   nan  3.5  inf -inf  5. ]
isnan: [False  True False False False False]
isfinite: [ True False  True False False  True]
finite values: [1.  3.5 5. ]
nanmean (finite only): 3.1666666666666665
nanstd (finite only): 1.649915822768611
nansum (finite only): 9.5
imputed: [1.    3.167 3.5   3.167 3.167 5.   ]


## 10. Sorting, Searching, and Set Operations

NumPy includes practical tools for ordering values, locating interesting positions, and comparing collections of values.

In [23]:
raw = np.array([7, 2, 9, 2, 5, 7, 1])

print("raw:", raw)
print("sorted:", np.sort(raw))
print("argsort:", np.argsort(raw))
print("unique:", np.unique(raw))
print("indices where raw > 5:", np.where(raw > 5)[0])
print("nonzero indices:", np.nonzero(raw))

raw: [7 2 9 2 5 7 1]
sorted: [1 2 2 5 7 7 9]
argsort: [6 1 3 4 0 5 2]
unique: [1 2 5 7 9]
indices where raw > 5: [0 2 5]
nonzero indices: (array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)


In [24]:
group_a = np.array([1, 2, 3, 4, 5])
group_b = np.array([4, 5, 6, 7])

print("intersection:", np.intersect1d(group_a, group_b))
print("difference a-b:", np.setdiff1d(group_a, group_b))
print("union:", np.union1d(group_a, group_b))
print("membership of [2,6,8] in group_a:", np.isin(np.array([2, 6, 8]), group_a))

intersection: [4 5]
difference a-b: [1 2 3]
union: [1 2 3 4 5 6 7]
membership of [2,6,8] in group_a: [ True False False]


### Top-k Selection and Ranking Patterns

**What this solves:** Efficiently retrieving highest/lowest scores without full sorting.

**How to use it:**
- `np.argpartition` gets top-k candidates in near-linear time.
- Apply `argsort` on that smaller subset to order final results.

**Important:** `argpartition` is fast but does not return fully sorted output by itself.

In [25]:
scores = np.array([0.22, 0.91, 0.35, 0.76, 0.81, 0.55])
k = 3

# Indices of k largest (unordered among themselves)
topk_idx = np.argpartition(scores, -k)[-k:]
# Order those top-k indices by score descending
ordered_topk = topk_idx[np.argsort(scores[topk_idx])[::-1]]

print('scores:', scores)
print('top-k indices:', ordered_topk)
print('top-k values:', scores[ordered_topk])

names = np.array(['a', 'b', 'c', 'd', 'e', 'f'])
print('paired ranking:', list(zip(names[ordered_topk], scores[ordered_topk])))

scores: [0.22 0.91 0.35 0.76 0.81 0.55]
top-k indices: [1 4 3]
top-k values: [0.91 0.81 0.76]
paired ranking: [('b', 0.91), ('e', 0.81), ('d', 0.76)]


## 11. Iteration, Enumeration, and Practical Patterns

Vectorization is usually best, but iteration still appears when we need row-wise inspection, custom formatting, or small algorithmic routines.

In [26]:
table = np.arange(1, 13).reshape(3, 4)

print("Iterating over rows:")
for row in table:
    print("row sum:", row.sum(), "| row:", row)

print()
print("Iterating with enumerate:")
for idx, row in enumerate(table):
    print(f"row {idx} mean = {row.mean():.2f}")

Iterating over rows:
row sum: 10 | row: [1 2 3 4]
row sum: 26 | row: [5 6 7 8]
row sum: 42 | row: [ 9 10 11 12]

Iterating with enumerate:
row 0 mean = 2.50
row 1 mean = 6.50
row 2 mean = 10.50


In [27]:
def moving_average(arr, window):
    result = []
    for i in range(len(arr) - window + 1):
        result.append(arr[i:i + window].mean())
    return np.array(result)

series = np.array([3, 5, 8, 10, 12, 15])
print("series:", series)
print("moving average window=3:", moving_average(series, 3))

series: [ 3  5  8 10 12 15]
moving average window=3: [ 5.33333333  7.66666667 10.         12.33333333]


### Sliding Windows for Feature Engineering

**What this solves:** Rolling-window features for time series and local statistics.

**How to use it:**
- `sliding_window_view` exposes overlapping windows as a view.
- Aggregate windows (mean/std/max/etc.) along the window axis.

**Important:** Window views can become large; great for clarity and prototyping, but watch memory.

In [28]:
from numpy.lib.stride_tricks import sliding_window_view

series = np.array([3, 5, 8, 10, 12, 15, 18])
windows = sliding_window_view(series, window_shape=3)
window_means = windows.mean(axis=1)

print('series:', series)
print('windows:\n', windows)
print('window means:', np.round(window_means, 3))

series: [ 3  5  8 10 12 15 18]
windows:
 [[ 3  5  8]
 [ 5  8 10]
 [ 8 10 12]
 [10 12 15]
 [12 15 18]]
window means: [ 5.333  7.667 10.    12.333 15.   ]


## 12. Random Number Generation and Sampling

Random arrays are useful for simulation, testing, and synthetic data generation. Prefer NumPy's modern Generator API (`np.random.default_rng`) over global `np.random.seed` patterns.

In [29]:
rng = np.random.default_rng(SEED)
uniform = rng.uniform(0, 1, size=(2, 3))
integers = rng.integers(1, 10, size=(2, 4))
normal = rng.normal(loc=0, scale=1, size=5)

print('uniform samples:\n', np.round(uniform, 3))
print('random integers:\n', integers)
print('normal samples:', np.round(normal, 3))

uniform samples:
 [[0.742 0.754 0.465]
 [0.104 0.967 0.321]]
random integers:
 [[8 2 4 8]
 [2 5 5 2]]
normal samples: [0.005 0.593 0.272 0.881 1.83 ]


In [30]:
rng_data = np.random.default_rng(SEED)
feature_1 = rng_data.normal(50, 10, size=8)
feature_2 = rng_data.normal(100, 15, size=8)
synthetic_dataset = np.column_stack((feature_1, feature_2))

# Independent generators are useful for isolating experiments.
rng_a = np.random.default_rng(2024)
rng_b = np.random.default_rng(2024)
print('Independent streams reproducible?', np.allclose(rng_a.normal(size=3), rng_b.normal(size=3)))

print('synthetic dataset shape:', synthetic_dataset.shape)
print(np.round(synthetic_dataset, 2))

Independent streams reproducible? True
synthetic dataset shape: (8, 2)
[[ 43.34  97.14]
 [ 50.97  86.88]
 [ 31.   100.07]
 [ 30.6  108.89]
 [ 35.89 104.08]
 [ 41.99 113.22]
 [ 42.66 127.46]
 [ 45.43  90.56]]


## 13. Linear Algebra Essentials

NumPy provides the array operations that underpin regression, optimization, geometry, and many machine learning models. In ML workflows, prefer solving systems (`solve`, `lstsq`) over explicitly forming matrix inverses.

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
A = np.array([
    [1, 1, 1], 
    [3, 4, 1],
    [1, 1, 1]
    ])
B = np.array([
    [7, 8, 2],
    [9, 10, 2],
    [11, 12, 2]
    ])

print("dot product:", np.dot(a, b))
print("inner product:", np.inner(a, b))
print("matrix multiplication using @:\n", A @ B)
print("matrix multiplication using np.dot:\n", np.dot(A,B))
print("transpose of B:\n", B.T)

dot product: 32
inner product: 32
matrix multiplication using @:
 [[27 30  6]
 [68 76 16]
 [27 30  6]]
matrix multiplication using np.dot:
 [[27 30  6]
 [68 76 16]
 [27 30  6]]
transpose of B:
 [[ 7  9 11]
 [ 8 10 12]
 [ 2  2  2]]


In [32]:
M = np.array([
    [2.0, 1.0],
    [1.0, 3.0]
])
target = np.array([1.0, 2.0])
solution = np.linalg.solve(M, target)

print('solution to Mx = target:', np.round(solution, 3))
print('determinant:', np.round(np.linalg.det(M), 3))
print('rank:', np.linalg.matrix_rank(M))

residual = np.linalg.norm(M @ solution - target)
print('solve residual norm:', residual)

eigenvalues, eigenvectors = np.linalg.eig(M)
print('eigenvalues:', np.round(eigenvalues, 3))
print('eigenvectors:\n', np.round(eigenvectors, 3))

solution to Mx = target: [0.2 0.6]
determinant: 5.0
rank: 2
solve residual norm: 2.220446049250313e-16
eigenvalues: [1.382 3.618]
eigenvectors:
 [[-0.851 -0.526]
 [ 0.526 -0.851]]


### Solving Linear Systems with `np.linalg.solve`

**What this solves:** Find `x` in `Ax = b` directly and numerically stably.

**Why prefer it:** `solve` avoids explicitly building `A^{-1}`, which is usually less stable and unnecessary for solving systems.

In [ ]:
A_sys = np.array([[3.0, 1.0], [1.0, 2.0]])
b_sys = np.array([9.0, 8.0])

x_solve = np.linalg.solve(A_sys, b_sys)
x_via_inv = np.linalg.inv(A_sys) @ b_sys

print('solution via solve:', np.round(x_solve, 6))
print('solution via inv(A) @ b:', np.round(x_via_inv, 6))
print('close?', np.allclose(x_solve, x_via_inv))
print('residual norm:', np.linalg.norm(A_sys @ x_solve - b_sys))

### ML-Relevant Linear Algebra (`norm`, `lstsq`, `pinv`, `svd`, `eigh`)

**What this solves:** Core numerical operations behind regression, diagnostics, and decomposition.

**How to use it:**
- `norm`: measure residual/error magnitude.
- `lstsq`: fit linear models when systems are over/under-determined.
- `pinv`: robust pseudo-inverse when exact inverse is not suitable.
- `svd`: factorization used in dimensionality reduction and conditioning analysis.
- `eigh`: eigen-decomposition for symmetric matrices (common in covariance workflows).

**Important:** In practice, prefer `solve/lstsq` over explicit matrix inversion.

In [33]:
X = np.array([
    [1.0, 1.0],
    [2.0, 1.0],
    [3.0, 1.0],
    [4.0, 1.0]
])
y = np.array([1.2, 1.9, 3.2, 3.9])

coef, *_ = np.linalg.lstsq(X, y, rcond=None)
y_hat = X @ coef
print('lstsq coefficients:', np.round(coef, 4))
print('residual norm:', np.round(np.linalg.norm(y - y_hat), 6))

XtX = X.T @ X
print('pseudo-inverse shape:', np.linalg.pinv(X).shape)
U, S, Vt = np.linalg.svd(X, full_matrices=False)
print('singular values:', np.round(S, 4))

sym = np.array([[2.0, 1.0], [1.0, 2.0]])
vals, vecs = np.linalg.eigh(sym)
print('eigh eigenvalues:', np.round(vals, 4))

data = np.array([[2., 4., 6.], [1., 3., 5.], [0., 2., 4.], [3., 5., 7.]])
print('covariance:\n', np.round(np.cov(data, rowvar=False), 3))
print('correlation:\n', np.round(np.corrcoef(data, rowvar=False), 3))

lstsq coefficients: [0.94 0.2 ]
residual norm: 0.268328
pseudo-inverse shape: (2, 4)
singular values: [5.7794 0.7738]
eigh eigenvalues: [1. 3.]
covariance:
 [[1.667 1.667 1.667]
 [1.667 1.667 1.667]
 [1.667 1.667 1.667]]
correlation:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Tensor Contractions: `einsum`, `tensordot`, and Batched Matmul

**What this solves:** Expressing multi-axis products clearly when dimensions grow beyond 2D.

**How to use it:**
- `einsum` gives explicit index-level control.
- `tensordot` contracts chosen axes directly.
- Batched `@` applies matrix multiply over leading batch dimensions.

**Important:** These are powerful debugging tools for dimension alignment, not just performance tricks.

In [34]:
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

matmul_1 = A @ B
matmul_2 = np.einsum('ik,kj->ij', A, B)
print('einsum equals @ ?', np.array_equal(matmul_1, matmul_2))

T1 = np.arange(24).reshape(2, 3, 4)
T2 = np.arange(20).reshape(4, 5)
contracted = np.tensordot(T1, T2, axes=([2], [0]))
print('tensordot output shape:', contracted.shape)  # (2, 3, 5)

batch_A = np.arange(24).reshape(2, 3, 4)
batch_B = np.arange(40).reshape(2, 4, 5)
batch_out = batch_A @ batch_B
print('batched matmul shape:', batch_out.shape)

einsum equals @ ? True
tensordot output shape: (2, 3, 5)
batched matmul shape: (2, 3, 5)


## 14. Coordinate Grids, Simulation Inputs, and Geometry

Coordinate grids make it easy to evaluate formulas across whole 2D domains. This is useful in plotting, simulation, optimization, and geometry.

In [35]:
x = np.linspace(-2, 2, 5)
y = np.linspace(-2, 2, 5)
X, Y = np.meshgrid(x, y)
Z = X**2 + Y**2

print("x: ", x ,"\ny: ", y)
print("X:\n", X)
print("Y:\n", Y)
print("X shape:", X.shape)
print("Y shape:", Y.shape)
print("surface Z = X^2 + Y^2:\n", Z)

x:  [-2. -1.  0.  1.  2.] 
y:  [-2. -1.  0.  1.  2.]
X:
 [[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
Y:
 [[-2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]]
X shape: (5, 5)
Y shape: (5, 5)
surface Z = X^2 + Y^2:
 [[8. 5. 4. 5. 8.]
 [5. 2. 1. 2. 5.]
 [4. 1. 0. 1. 4.]
 [5. 2. 1. 2. 5.]
 [8. 5. 4. 5. 8.]]


In [36]:
x_line = np.linspace(0, 4, 5)
y_line = np.linspace(0, 4, 5)
X_plane, Y_plane = np.meshgrid(x_line, y_line)
plane = 2 * X_plane + 3 * Y_plane + 5

print("plane values for z = 2x + 3y + 5:\n", plane)
print("center point value:", plane[2, 2])

plane values for z = 2x + 3y + 5:
 [[ 5.  7.  9. 11. 13.]
 [ 8. 10. 12. 14. 16.]
 [11. 13. 15. 17. 19.]
 [14. 16. 18. 20. 22.]
 [17. 19. 21. 23. 25.]]
center point value: 15.0


## 15. Performance Mindset and Memory Awareness

A good NumPy workflow is not only correct; it is also conscious of speed, memory, array layout, and whether operations create views or copies.

In [37]:
large = np.arange(1000000, dtype=np.float64)
view = large[:5]
copy = large[:5].copy()

print("large dtype:", large.dtype)
print("large nbytes:", large.nbytes)
print("first five via view:", view)
print("copy shares memory?", np.shares_memory(large, copy))
print("view shares memory?", np.shares_memory(large, view))

large dtype: float64
large nbytes: 8000000
first five via view: [0. 1. 2. 3. 4.]
copy shares memory? False
view shares memory? True


In [38]:
small = np.arange(1, 3000001, dtype=np.int64)
t = time()
python_sum = sum(int(value) * 2 for value in small)
print('python time: ', time()-t)
t = time()
numpy_sum = np.sum(small * 2)
print('numpy time: ', time()-t)

print('python_sum:', python_sum)
print('numpy_sum:', numpy_sum)
print('same result:', python_sum == numpy_sum)
print('Vectorized NumPy usually wins more clearly as data gets larger.')

python time:  0.3882174491882324
numpy time:  0.010001659393310547
python_sum: 9000003000000
numpy_sum: 9000003000000
same result: True
Vectorized NumPy usually wins more clearly as data gets larger.


### Contiguity, Views, and Copy Behavior

**What this solves:** Understanding surprising performance/interoperability issues caused by memory layout.

**How to use it:**
- Check `arr.flags['C_CONTIGUOUS']`.
- Remember transpose often creates non-contiguous views.
- Use `np.ascontiguousarray` when downstream code needs contiguous memory.

**Important:** `astype(copy=False)` only avoids copying when dtype/layout already match.

In [39]:
arr = np.arange(12, dtype=np.float32).reshape(3, 4)
arr_T = arr.T

print('arr C-contiguous?', arr.flags['C_CONTIGUOUS'])
print('arr_T C-contiguous?', arr_T.flags['C_CONTIGUOUS'])
print('arr_T shares memory with arr?', np.shares_memory(arr, arr_T))

arr_T_contig = np.ascontiguousarray(arr_T)
print('arr_T_contig C-contiguous?', arr_T_contig.flags['C_CONTIGUOUS'])
print('arr_T_contig shares memory with arr?', np.shares_memory(arr, arr_T_contig))

float64_view_if_possible = arr.astype(np.float32, copy=False)
print('astype(copy=False) returned same object?', float64_view_if_possible is arr)

arr C-contiguous? True
arr_T C-contiguous? False
arr_T shares memory with arr? True
arr_T_contig C-contiguous? True
arr_T_contig shares memory with arr? False
astype(copy=False) returned same object? True


**Reshape note:** `reshape` returns a view when possible, but may return a copy when memory layout prevents a view (common after transpose/non-contiguous operations).

In [ ]:
base = np.arange(12).reshape(3, 4)
reshaped_view = base.reshape(2, 6)

non_contig = base.T  # typically non-contiguous view
reshaped_after_transpose = non_contig.reshape(2, 6)

print('reshape on contiguous shares memory?', np.shares_memory(base, reshaped_view))
print('transpose is C-contiguous?', non_contig.flags['C_CONTIGUOUS'])
print('reshape after transpose shares memory?', np.shares_memory(non_contig, reshaped_after_transpose))

### Saving/Loading Arrays and Numerical Comparison Utilities

**What this solves:** Reliable persistence and correctness checks in real projects.

**How to use it:**
- `save/load` for one array (`.npy`).
- `savez/savez_compressed` for multiple named arrays (`.npz`).
- `array_equal` for exact checks, `allclose` for floating-point tolerance.

**Important:** For floats, prefer `allclose` unless bitwise-exact equality is required.

In [40]:
from pathlib import Path
import tempfile

payload = np.arange(6).reshape(2, 3)
features = np.array([[1.0, 2.0], [3.0, 4.0]])
labels = np.array([0, 1])

with tempfile.TemporaryDirectory() as tmp:
    tmp_path = Path(tmp)

    np.save(tmp_path / 'payload.npy', payload)
    loaded_payload = np.load(tmp_path / 'payload.npy')

    np.savez(tmp_path / 'dataset.npz', X=features, y=labels)
    np.savez_compressed(tmp_path / 'dataset_compressed.npz', X=features, y=labels)
    with np.load(tmp_path / 'dataset.npz') as archive:
        keys = list(archive.files)

    print('payload round-trip exact?', np.array_equal(payload, loaded_payload))
    print('archive keys:', keys)

baseline = np.array([0.1 + 0.2, 0.3])
print('array_equal on floats:', np.array_equal(baseline, np.array([0.3, 0.3])))
print('allclose on floats:', np.allclose(baseline, np.array([0.3, 0.3]), atol=1e-8))

payload round-trip exact? True
archive keys: ['X', 'y']
array_equal on floats: False
allclose on floats: True


## 16. NumPy for Machine Learning Foundations

Many ML workflows start as array operations: building feature matrices, transforming columns, applying matrix math, managing shapes, and using numerically stable formulas.

In [41]:
features = np.array([
    [170, 65],
    [180, 80],
    [175, 72],
    [160, 55]
], dtype=float)
target = np.array([0, 1, 1, 0])

feature_means = features.mean(axis=0)
feature_stds = features.std(axis=0)
standardized = (features - feature_means) / feature_stds

print("features shape:", features.shape)
print("target shape:", target.shape)
print("means:", np.round(feature_means, 2))
print("stds:", np.round(feature_stds, 2))
print("standardized features:\n", np.round(standardized, 3))

features shape: (4, 2)
target shape: (4,)
means: [171.25  68.  ]
stds: [7.4  9.19]
standardized features:
 [[-0.169 -0.326]
 [ 1.183  1.305]
 [ 0.507  0.435]
 [-1.521 -1.414]]


In [42]:
X = np.array([
    [1, 1.0, 2.0],
    [1, 2.0, 1.0],
    [1, 3.0, 4.0]
])
weights = np.array([0.5, 1.2, -0.7])
predictions = X @ weights

print("design matrix X:\n", X)
print("weights:", weights)
print("predictions:", np.round(predictions, 3))

design matrix X:
 [[1. 1. 2.]
 [1. 2. 1.]
 [1. 3. 4.]]
weights: [ 0.5  1.2 -0.7]
predictions: [0.3 2.2 1.3]


### Numerical Stability Patterns (Softmax, Log, and Safe Division)

**What this solves:** Preventing overflow, `-inf`, and divide-by-zero issues in ML math.

**How to use it:**
- Softmax: subtract max logit first.
- Logs: clip probabilities before `log`.
- Division: add small epsilon to denominators when zeros are possible.

**Important:** Stable formulas often matter more than algorithm choice for reliable training/inference behavior.

In [43]:
logits = np.array([1000.0, 1001.0, 999.0])

# Unstable (can overflow on large values)
with np.errstate(over='ignore', invalid='ignore'):
    unstable_softmax = np.exp(logits) / np.sum(np.exp(logits))

# Stable softmax: subtract max first
shifted = logits - np.max(logits)
stable_softmax = np.exp(shifted) / np.sum(np.exp(shifted))

probs = np.array([0.0, 1e-12, 0.4, 0.6])
safe_log = np.log(np.clip(probs, 1e-9, 1.0))

numerator = np.array([1.0, 2.0, 3.0])
denominator = np.array([1.0, 0.0, 2.0])
safe_ratio = numerator / (denominator + 1e-9)

print('unstable softmax finite?', np.all(np.isfinite(unstable_softmax)))
print('stable softmax:', np.round(stable_softmax, 6), 'sum=', stable_softmax.sum())
print('safe log:', np.round(safe_log, 4))
print('safe ratio:', np.round(safe_ratio, 4))

unstable softmax finite? False
stable softmax: [0.244728 0.665241 0.090031] sum= 0.9999999999999999
safe log: [-20.7233 -20.7233  -0.9163  -0.5108]
safe ratio: [1.0e+00 2.0e+09 1.5e+00]


### Common ML Array Recipes

**What this solves:** Frequently repeated building blocks in preprocessing and evaluation.

**How to use it:**
- One-hot encode labels with `eye()[labels]`.
- Compute pairwise distances with broadcasting.
- Compute cosine similarity via normalized dot products.
- Build confusion matrices with indexed accumulation (`np.add.at`).

**Important:** These patterns scale from toy examples to production preprocessing logic.

In [44]:
labels = np.array([2, 0, 1, 2, 1])
num_classes = labels.max() + 1
one_hot = np.eye(num_classes, dtype=int)[labels]
print('one-hot:\n', one_hot)

P = np.array([[0., 0.], [1., 1.], [2., 0.]])
Q = np.array([[0., 1.], [2., 1.]])

# Pairwise Euclidean distances using broadcasting
pairwise = np.linalg.norm(P[:, None, :] - Q[None, :, :], axis=2)
print('pairwise distances:\n', np.round(pairwise, 3))

# Cosine similarity between rows of P and Q
P_norm = np.linalg.norm(P, axis=1, keepdims=True) + 1e-12
Q_norm = np.linalg.norm(Q, axis=1, keepdims=True) + 1e-12
cosine = (P @ Q.T) / (P_norm * Q_norm.T)
print('cosine similarity:\n', np.round(cosine, 3))

y_true = np.array([0, 1, 2, 1, 0, 2, 1])
y_pred = np.array([0, 2, 2, 1, 0, 1, 1])
cm = np.zeros((3, 3), dtype=int)
np.add.at(cm, (y_true, y_pred), 1)
print('confusion matrix:\n', cm)

one-hot:
 [[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]]
pairwise distances:
 [[1.    2.236]
 [1.    1.   ]
 [2.236 1.   ]]
cosine similarity:
 [[0.    0.   ]
 [0.707 0.949]
 [0.    0.894]]
confusion matrix:
 [[2 0 0]
 [0 2 1]
 [0 1 1]]


### Feature Engineering with `np.where`

`np.where` is useful for rule-based feature creation without loops, for example threshold flags, piecewise transformations, and capped values.

In [ ]:
income = np.array([28_000, 45_000, 72_000, 130_000], dtype=float)
credit_score = np.array([580, 640, 710, 780])

high_income_flag = np.where(income >= 70_000, 1, 0)
risk_band = np.where(credit_score < 620, 'high', np.where(credit_score < 700, 'medium', 'low'))
log_income_piecewise = np.where(income < 50_000, np.log1p(income), np.log1p(income) * 1.05)

print('high_income_flag:', high_income_flag)
print('risk_band:', risk_band)
print('engineered piecewise feature:', np.round(log_income_piecewise, 4))

## 17. Real Use Case Example

In [45]:
rng_ml = np.random.default_rng(SEED)

# Synthetic regression data
n_samples = 12
study_hours = rng_ml.integers(1, 10, size=n_samples)
practice_tests = rng_ml.integers(50, 100, size=n_samples)
noise = rng_ml.normal(0, 3, size=n_samples)
exam_scores = 5 * study_hours + 0.4 * practice_tests + noise

X = np.column_stack([np.ones(n_samples), study_hours, practice_tests])
y = exam_scores

# Fit linear regression with least squares
coef, residuals, rank, singular_vals = np.linalg.lstsq(X, y, rcond=None)
preds = X @ coef
mae = np.mean(np.abs(preds - y))

print('columns: bias, study_hours, practice_tests')
print('coefficients:', np.round(coef, 3))
print('mean absolute error:', np.round(mae, 3))
print('rank of design matrix:', rank)
print('top 3 actual exam scores:', np.round(np.sort(y)[-3:], 2))
print('top 3 predicted exam scores:', np.round(np.sort(preds)[-3:], 2))

columns: bias, study_hours, practice_tests
coefficients: [7.769 4.891 0.329]
mean absolute error: 1.865
rank of design matrix: 3
top 3 actual exam scores: [61.64 69.91 81.87]
top 3 predicted exam scores: [61.77 72.31 80.45]


Best practices:

- Check `shape` before arithmetic and matrix operations.
- Use `.copy()` when you need independence from the original array.
- Use `keepdims=True` when you plan to broadcast reduced values back.
- Prefer `np.random.default_rng(seed)` over global RNG state.
- Use `np.allclose` for floating-point comparisons instead of exact equality.
- Prefer `solve` or `lstsq` over explicit matrix inversion.
- Use stable formulas (`max` shifting, clipping, epsilon guards) for ML numerics.

## 18. Quick Reference Cheat Sheet

This section is a compact review page for the operations that come up most often.

Core patterns to remember:

- Create arrays: `np.array`, `np.arange`, `np.linspace`, `np.zeros`, `np.ones`, `np.full`, `np.eye`
- Inspect arrays: `.shape`, `.ndim`, `.size`, `.dtype`, `.nbytes`, `.strides`
- Reshape arrays: `.reshape`, `.ravel`, `.flatten`, `.T`, `np.expand_dims`, `np.squeeze`, `np.newaxis`
- Combine/split arrays: `np.concatenate`, `np.stack`, `np.vstack`, `np.hstack`, `np.column_stack`, `np.split`
- Aggregate values: `.sum`, `.mean`, `np.median`, `.std`, `.min`, `.max`, `.argmin`, `.argmax`, `keepdims=True`
- Handle missing values: `np.isnan`, `np.isfinite`, `np.nanmean`, `np.nanstd`, `np.nansum`
- Filter values: comparisons, boolean masks, `np.where`, `np.any`, `np.all`
- Sort/select: `np.sort`, `np.argsort`, `np.argpartition`, `np.unique`
- Linear algebra: `np.dot`, `@`, `np.linalg.solve`, `np.linalg.norm`, `np.linalg.lstsq`, `np.linalg.svd`
- Tensor ops: `np.einsum`, `np.tensordot`
- Robust checks: `np.array_equal`, `np.allclose`
- IO: `np.save`, `np.load`, `np.savez`, `np.savez_compressed`

In [46]:
quick = np.arange(1, 10).reshape(3, 3)

print("quick array:\n", quick)
print("shape:", quick.shape)
print("transpose:\n", quick.T)
print("row means:", quick.mean(axis=1))
print("values > 5:", quick[quick > 5])
print("determinant:", np.linalg.det(quick))

quick array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
row means: [2. 5. 8.]
values > 5: [6 7 8 9]
determinant: 0.0


## 19. Closing Notes and Next Steps

This notebook now covers core NumPy skills plus ML-critical patterns: shape/axis fluency, missing-data handling, modern RNG usage, stable numerics, practical linear algebra, tensor operations, memory layout awareness, and reference-quality utility workflows.

Key habits worth carrying forward:

- Think in arrays and shapes, not one element at a time.
- Inspect metadata early when debugging.
- Prefer vectorized transformations when possible.
- Stay aware of views, copies, and `dtype` choices.
- Connect every operation back to a real use case such as cleaning data, building features, simulation, or modeling.